/* ============================================================
   elegant.js — "Prestige" template
   Cream background, deep navy left panel with gold ornament,
   gold vertical separator, Playfair Display 80px name,
   gold diamond-rule, laurel seal, cursive signature.
   ============================================================ */

module.exports = function elegantTemplate(data, options = {}) {
  const navy = "#1B365D";
  const gold = "#C9A84C";
  const cream = "#F9F6EE";

  const { recipient = {}, certificate = {}, verifyId, qrDataUrl } = data;
  const recipientName = recipient.name            || "Recipient Name";
  const certTitle     = certificate.title         || "Certificate of Completion";
  const courseName    = certificate.course        || "";
  const rawDate       = certificate.date
    ? new Date(certificate.date + "T12:00:00").toLocaleDateString("en-US", { year:"numeric", month:"long", day:"numeric" })
    : new Date().toLocaleDateString("en-US", { year:"numeric", month:"long", day:"numeric" });
  const issuerName    = certificate.issuer        || "";
  const issuerTitle   = certificate.issuer_title  || "";
  const watermark     = options.watermark || false;

  const qrHtml = qrDataUrl
    ? `<img src="${qrDataUrl}" class="qr-img" alt="Verify"/>`
    : "";

  const watermarkHtml = watermark
    ? `<div class="watermark">Generated by BuildCertificates.com</div>`
    : "";

  // Laurel + shield SVG seal
  const sealSvg = `<svg viewBox="0 0 90 90" xmlns="http://www.w3.org/2000/svg" style="width:90px;height:90px;">
  <circle cx="45" cy="45" r="43" fill="none" stroke="${gold}" stroke-width="2"/>
  <circle cx="45" cy="45" r="36" fill="none" stroke="${gold}" stroke-width="0.8" stroke-dasharray="3,3"/>
  <!-- Laurel left -->
  <path d="M18,55 Q12,48 15,40 Q18,33 23,36 Q18,42 20,48 Q22,54 18,55Z" fill="${gold}" opacity="0.8"/>
  <path d="M22,62 Q14,56 16,47 Q18,39 24,41 Q20,47 21,54 Q23,60 22,62Z" fill="${gold}" opacity="0.7"/>
  <path d="M27,68 Q18,63 19,54 Q20,45 27,47 Q23,53 24,60 Q26,66 27,68Z" fill="${gold}" opacity="0.6"/>
  <!-- Laurel right -->
  <path d="M72,55 Q78,48 75,40 Q72,33 67,36 Q72,42 70,48 Q68,54 72,55Z" fill="${gold}" opacity="0.8"/>
  <path d="M68,62 Q76,56 74,47 Q72,39 66,41 Q70,47 69,54 Q67,60 68,62Z" fill="${gold}" opacity="0.7"/>
  <path d="M63,68 Q72,63 71,54 Q70,45 63,47 Q67,53 66,60 Q64,66 63,68Z" fill="${gold}" opacity="0.6"/>
  <!-- Shield -->
  <path d="M45,18 L60,24 L60,44 Q60,60 45,68 Q30,60 30,44 L30,24 Z" fill="${navy}" opacity="0.9"/>
  <path d="M45,22 L56,27 L56,44 Q56,57 45,64 Q34,57 34,44 L34,27 Z" fill="none" stroke="${gold}" stroke-width="1" opacity="0.6"/>
  <!-- Book icon in shield -->
  <rect x="38" y="34" width="14" height="10" rx="0.5" fill="none" stroke="${gold}" stroke-width="1.2"/>
  <line x1="45" y1="34" x2="45" y2="44" stroke="${gold}" stroke-width="1"/>
  <line x1="40" y1="37.5" x2="44" y2="37.5" stroke="${gold}" stroke-width="0.7"/>
  <line x1="40" y1="40" x2="44" y2="40" stroke="${gold}" stroke-width="0.7"/>
  <line x1="46" y1="37.5" x2="50" y2="37.5" stroke="${gold}" stroke-width="0.7"/>
  <line x1="46" y1="40" x2="50" y2="40" stroke="${gold}" stroke-width="0.7"/>
  <!-- Bottom text -->
  <line x1="33" y1="72" x2="57" y2="72" stroke="${gold}" stroke-width="0.5"/>
</svg>`;

  // Gold ornament for the left panel (centered vertically)
  const panelOrnament = `<svg viewBox="0 0 60 200" xmlns="http://www.w3.org/2000/svg" style="width:60px;height:200px;">
  <line x1="30" y1="0" x2="30" y2="200" stroke="${gold}" stroke-width="0.5" stroke-opacity="0.4"/>
  <circle cx="30" cy="30" r="4" fill="${gold}" opacity="0.6"/>
  <circle cx="30" cy="30" r="7" fill="none" stroke="${gold}" stroke-width="0.8" opacity="0.4"/>
  <path d="M30,40 Q22,55 30,70 Q38,55 30,40Z" fill="${gold}" opacity="0.4"/>
  <path d="M30,80 L26,90 L30,100 L34,90 Z" fill="${gold}" opacity="0.3"/>
  <circle cx="30" cy="115" r="4" fill="${gold}" opacity="0.5"/>
  <path d="M30,125 Q22,140 30,155 Q38,140 30,125Z" fill="${gold}" opacity="0.3"/>
  <circle cx="30" cy="170" r="4" fill="${gold}" opacity="0.6"/>
  <circle cx="30" cy="170" r="7" fill="none" stroke="${gold}" stroke-width="0.8" opacity="0.4"/>
</svg>`;

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,700;0,800;1,700&family=Cinzel:wght@400;600;700&family=Dancing+Script:wght@600;700&family=EB+Garamond:ital,wght@0,400;1,400&display=swap');

  * { margin:0; padding:0; box-sizing:border-box; }
  html, body { width:11in; height:8.5in; overflow:hidden; background:${cream}; }
  .page { width:11in; height:8.5in; position:relative; background:${cream}; display:flex; overflow:hidden; }

  /* ── Left navy panel ── */
  .left-panel {
    width: 1.4in;
    background: ${navy};
    flex-shrink: 0;
    position: relative;
    display: flex;
    align-items: center;
    justify-content: center;
  }
  /* Gold separator line */
  .left-panel::after {
    content: '';
    position: absolute;
    right: -1px; top: 8%; bottom: 8%;
    width: 2px;
    background: linear-gradient(180deg, transparent, ${gold} 15%, ${gold} 85%, transparent);
  }

  /* ── Main content ── */
  .main {
    flex: 1;
    display: flex;
    flex-direction: column;
    padding: 0.52in 0.6in 0.22in 0.5in;
  }

  /* Top decorative rule */
  .top-rule {
    display: flex;
    align-items: center;
    gap: 10px;
    margin-bottom: 0.22in;
  }
  .top-rule-line { flex:1; height:1px; background:linear-gradient(90deg, ${gold}, transparent); }
  .top-rule-diamond { width:8px; height:8px; background:${gold}; transform:rotate(45deg); flex-shrink:0; }

  /* Certificate title */
  .cert-title {
    font-family: 'Cinzel', serif;
    font-size: 22px;
    font-weight: 600;
    color: ${navy};
    letter-spacing: 6px;
    text-transform: uppercase;
    margin-bottom: 0.12in;
  }

  /* Presented to */
  .presented {
    font-family: 'EB Garamond', serif;
    font-style: italic;
    font-size: 20px;
    color: #888;
    margin-bottom: 0.04in;
  }

  /* Recipient name — the hero */
  .recipient-name {
    font-family: 'Playfair Display', serif;
    font-size: 78px;
    font-weight: 800;
    color: ${navy};
    line-height: 0.95;
    letter-spacing: -1px;
    margin-bottom: 0.1in;
  }

  /* Gold diamond rule below name */
  .name-rule {
    display: flex;
    align-items: center;
    gap: 8px;
    margin-bottom: 0.12in;
  }
  .nr-line { flex:1; height:1.5px; background:linear-gradient(90deg, ${gold}, rgba(201,168,76,0.2)); }
  .nr-diamond { width:8px; height:8px; background:${gold}; transform:rotate(45deg); flex-shrink:0; }
  .nr-diamond-sm { width:5px; height:5px; background:${gold}; transform:rotate(45deg); flex-shrink:0; opacity:0.6; }

  /* Course */
  .course-intro { font-family:'EB Garamond',serif; font-style:italic; font-size:18px; color:#999; margin-bottom:4px; }
  .course-name  { font-family:'Cinzel',serif; font-size:22px; font-weight:600; color:${navy}; letter-spacing:3px; text-transform:uppercase; margin-bottom:0.08in; }

  /* Date & Issuer */
  .meta-row { display:flex; flex-direction:column; gap:3px; margin-bottom:0; }
  .meta-date   { font-family:'EB Garamond',serif; font-size:16px; color:#aaa; }
  .meta-issuer { font-family:'Cinzel',serif; font-size:16px; font-weight:600; color:${navy}; letter-spacing:2px; }

  /* Bottom footer */
  .footer {
    margin-top: auto;
    display: flex;
    align-items: flex-end;
    justify-content: space-between;
  }

  .sig-block { display:flex; flex-direction:column; }
  .sig-label  { font-family:'EB Garamond',serif; font-size:13px; color:#bbb; letter-spacing:2px; text-transform:uppercase; margin-bottom:3px; }
  .sig-script { font-family:'Dancing Script',cursive; font-size:32px; color:#444; line-height:1; margin-bottom:5px; }
  .sig-line   { width:200px; height:1px; background:#ccc; margin-bottom:5px; }
  .sig-name   { font-family:'EB Garamond',serif; font-size:15px; color:#888; }

  .seal-wrap { display:flex; align-items:center; justify-content:center; }

  .qr-wrap { display:flex; flex-direction:column; align-items:flex-end; }
  .qr-img  { width:60px; height:60px; border:1px solid ${gold}; padding:2px; }

  .watermark { position:absolute; bottom:3px; left:1.4in; right:0; text-align:center; font-size:8px; color:#ccc; font-family:'EB Garamond',serif; }
</style>
</head>
<body>
<div class="page">

  <!-- Left navy panel -->
  <div class="left-panel">
    ${panelOrnament}
  </div>

  <!-- Main content -->
  <div class="main">
    <div class="top-rule">
      <div class="top-rule-line"></div>
      <div class="top-rule-diamond"></div>
    </div>

    <div class="cert-title">${certTitle}</div>
    <div class="presented">This is proudly presented to</div>
    <div class="recipient-name">${recipientName}</div>

    <div class="name-rule">
      <div class="nr-line"></div>
      <div class="nr-diamond-sm"></div>
      <div class="nr-diamond"></div>
      <div class="nr-diamond-sm"></div>
    </div>

    ${courseName ? `
    <div class="course-intro">For successfully completing</div>
    <div class="course-name">${courseName}</div>
    ` : ""}

    <div class="meta-row">
      <div class="meta-date">${rawDate}</div>
      ${issuerName ? `<div class="meta-issuer">${issuerName}</div>` : ""}
    </div>

    <div class="footer">
      <div class="sig-block">
        <div class="sig-label">Authorized Signature</div>
        <div class="sig-script">${issuerName || "Signature"}</div>
        <div class="sig-line"></div>
        ${issuerTitle ? `<div class="sig-name">${issuerTitle}</div>` : ""}
      </div>
      <div class="seal-wrap">${sealSvg}</div>
      <div class="qr-wrap">${qrHtml}</div>
    </div>
  </div>

  ${watermarkHtml}
</div>
</body>
</html>`;
};
