/* ============================================================
   elegant.js — Elegant certificate template
   Matches mockup: cream bg, full ornate gold border with SVG
   filigree corners, title inside frame, 72px navy recipient,
   centered issuer, cursive sig, shield seal center, QR right.
   ============================================================ */

module.exports = function elegantTemplate(data, options = {}) {
  const navy = "#1B365D";
  const gold = "#C5A55A";

  const { recipient = {}, certificate = {}, verifyId, qrDataUrl } = data;
  const recipientName = recipient.name           || "Recipient Name";
  const certTitle     = certificate.title        || "Certificate of Completion";
  const courseName    = certificate.course       || "";
  const rawDate       = certificate.date
    ? new Date(certificate.date + "T12:00:00").toLocaleDateString("en-US", { year:"numeric", month:"long", day:"numeric" })
    : new Date().toLocaleDateString("en-US", { year:"numeric", month:"long", day:"numeric" });
  const issuerName    = certificate.issuer       || "";
  const issuerTitle   = certificate.issuer_title || "";
  const watermark     = options.watermark || false;

  // Split title at midpoint for 2-line layout
  const words = certTitle.split(" ");
  const mid   = Math.ceil(words.length / 2);
  const line1 = words.slice(0, mid).join(" ").toUpperCase();
  const line2 = words.slice(mid).join(" ").toUpperCase();

  const courseHtml = courseName ? `
    <div class="course-text">FOR SUCCESSFULLY COMPLETING</div>
    <div class="course-name">${courseName.toUpperCase()}</div>
  ` : "";

  const qrHtml = qrDataUrl ? `
    <div class="qr-wrap">
      <img src="${qrDataUrl}" class="qr-img" alt="Verify" />
    </div>
  ` : `<div class="qr-wrap"></div>`;

  // SVG filigree corner (top-left; others are CSS-rotated)
  const corner = `<svg class="corner-svg" viewBox="0 0 120 120" xmlns="http://www.w3.org/2000/svg">
  <!-- Filled block -->
  <rect x="0" y="0" width="22" height="22" fill="${navy}"/>
  <!-- Gold accent line from block along top -->
  <line x1="22" y1="4" x2="116" y2="4" stroke="${gold}" stroke-width="2.5"/>
  <line x1="22" y1="11" x2="116" y2="11" stroke="${navy}" stroke-width="7"/>
  <line x1="22" y1="11" x2="116" y2="11" stroke="${gold}" stroke-width="1" stroke-opacity="0.6"/>
  <!-- Gold accent line from block along left -->
  <line x1="4" y1="22" x2="4" y2="116" stroke="${gold}" stroke-width="2.5"/>
  <line x1="11" y1="22" x2="11" y2="116" stroke="${navy}" stroke-width="7"/>
  <line x1="11" y1="22" x2="11" y2="116" stroke="${gold}" stroke-width="1" stroke-opacity="0.6"/>
  <!-- Filigree scrollwork at corner intersection -->
  <path d="M22,22 Q30,22 30,30 Q30,38 38,38" stroke="${gold}" stroke-width="1.5" fill="none"/>
  <path d="M22,22 Q22,30 30,30 Q38,30 38,38" stroke="${gold}" stroke-width="1" fill="none" opacity="0.6"/>
  <circle cx="38" cy="38" r="3" fill="${gold}" opacity="0.7"/>
  <!-- Small decorative fleur tip on top border -->
  <path d="M56,4 L56,0 M56,0 L52,4 M56,0 L60,4" stroke="${gold}" stroke-width="1.2" fill="none"/>
  <!-- Small decorative fleur tip on left border -->
  <path d="M4,56 L0,56 M0,56 L4,52 M0,56 L4,60" stroke="${gold}" stroke-width="1.2" fill="none"/>
</svg>`;

  // Institutional shield seal SVG (center bottom)
  const sealSvg = `<svg class="seal-svg" viewBox="0 0 80 80" xmlns="http://www.w3.org/2000/svg">
  <path d="M40,4 L68,14 L68,42 Q68,62 40,76 Q12,62 12,42 L12,14 Z" fill="none" stroke="${gold}" stroke-width="2"/>
  <path d="M40,10 L62,18 L62,42 Q62,58 40,70 Q18,58 18,42 L18,18 Z" fill="${navy}" opacity="0.08"/>
  <!-- Laurel left -->
  <path d="M20,50 Q16,46 18,42 Q20,38 22,40" stroke="${gold}" stroke-width="1.2" fill="none"/>
  <path d="M20,50 Q15,48 16,44 Q17,40 20,42" stroke="${gold}" stroke-width="1" fill="none" opacity="0.7"/>
  <!-- Laurel right -->
  <path d="M60,50 Q64,46 62,42 Q60,38 58,40" stroke="${gold}" stroke-width="1.2" fill="none"/>
  <path d="M60,50 Q65,48 64,44 Q63,40 60,42" stroke="${gold}" stroke-width="1" fill="none" opacity="0.7"/>
  <!-- Open book icon -->
  <rect x="30" y="30" width="20" height="14" rx="1" fill="none" stroke="${navy}" stroke-width="1.5"/>
  <line x1="40" y1="30" x2="40" y2="44" stroke="${navy}" stroke-width="1.2"/>
  <line x1="33" y1="34" x2="38" y2="34" stroke="${navy}" stroke-width="0.8"/>
  <line x1="33" y1="37" x2="38" y2="37" stroke="${navy}" stroke-width="0.8"/>
  <line x1="42" y1="34" x2="47" y2="34" stroke="${navy}" stroke-width="0.8"/>
  <line x1="42" y1="37" x2="47" y2="37" stroke="${navy}" stroke-width="0.8"/>
  <!-- Bottom dot accent -->
  <circle cx="40" cy="60" r="2" fill="${gold}"/>
</svg>`;

  const watermarkHtml = watermark ? `<div class="watermark">Generated by BuildCertificates — buildcertificates.com</div>` : "";

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Cinzel:wght@400;600;700&family=Cormorant+Garamond:ital,wght@0,400;0,600;1,400;1,600&family=Dancing+Script:wght@600&family=EB+Garamond:ital,wght@0,400;1,400&display=swap');
  * { margin:0; padding:0; box-sizing:border-box; }
  html, body { width:11in; height:8.5in; overflow:hidden; background:#FDFAF3; }
  .page { width:11in; height:8.5in; position:relative; background:#FDFAF3; display:flex; flex-direction:column; align-items:center; justify-content:flex-start; overflow:hidden; }

  /* ── Corners ── */
  .corner-svg { width:120px; height:120px; position:absolute; }
  .c-tl { top:0; left:0; }
  .c-tr { top:0; right:0; transform:scaleX(-1); }
  .c-bl { bottom:0; left:0; transform:scaleY(-1); }
  .c-br { bottom:0; right:0; transform:scale(-1); }

  /* ── Border lines (connecting corners) ── */
  .b-top    { position:absolute; top:11px; left:112px; right:112px; height:7px; background:${navy}; }
  .b-top::before { content:''; position:absolute; top:-4px; left:0; right:0; height:2.5px; background:${gold}; }
  .b-bottom { position:absolute; bottom:11px; left:112px; right:112px; height:7px; background:${navy}; }
  .b-bottom::before { content:''; position:absolute; bottom:-4px; left:0; right:0; height:2.5px; background:${gold}; }
  .b-left   { position:absolute; left:11px; top:112px; bottom:112px; width:7px; background:${navy}; }
  .b-left::before { content:''; position:absolute; left:-4px; top:0; bottom:0; width:2.5px; background:${gold}; }
  .b-right  { position:absolute; right:11px; top:112px; bottom:112px; width:7px; background:${navy}; }
  .b-right::before { content:''; position:absolute; right:-4px; top:0; bottom:0; width:2.5px; background:${gold}; }

  /* ── Inner gold rule ── */
  .inner-border { position:absolute; top:24px; left:24px; right:24px; bottom:24px; border:1px solid ${gold}; pointer-events:none; }

  /* ── Content area ── */
  .content { position:relative; z-index:5; display:flex; flex-direction:column; align-items:center; justify-content:center; width:100%; flex:1; padding:0.6in 1.1in 0; }

  .cert-title-1 { font-family:'Cinzel',serif; font-size:52px; font-weight:700; color:${navy}; letter-spacing:6px; text-align:center; line-height:1; }
  .cert-title-2 { font-family:'Cinzel',serif; font-size:38px; font-weight:600; color:${navy}; letter-spacing:4px; text-align:center; line-height:1; margin-bottom:10px; }
  ${!line2 ? `.cert-title-1 { font-size:40px; }` : ""}

  .presented-to { font-family:'EB Garamond',serif; font-style:italic; font-size:16px; color:#666; margin-bottom:5px; }

  .recipient-name { font-family:'Cormorant Garamond',serif; font-size:72px; font-weight:700; color:${navy}; text-align:center; line-height:1; letter-spacing:2px; margin-bottom:4px; }

  .name-rule { width:480px; height:1.5px; background:linear-gradient(90deg,transparent,${gold} 20%,${gold} 80%,transparent); margin:6px auto 12px; }

  .course-text { font-family:'Cinzel',serif; font-size:13px; font-weight:600; color:#444; letter-spacing:3px; text-align:center; margin-bottom:4px; }
  .course-name  { font-family:'Cinzel',serif; font-size:15px; font-weight:700; color:#222; letter-spacing:3px; text-align:center; margin-bottom:8px; }

  .date-text { font-family:'EB Garamond',serif; font-size:14px; color:#888; text-align:center; margin-bottom:6px; }

  .issuer-centered { font-family:'Cinzel',serif; font-size:16px; font-weight:700; color:${navy}; letter-spacing:4px; text-align:center; margin-bottom:0; }

  /* ── Footer row ── */
  .footer-row { position:relative; z-index:5; display:flex; align-items:flex-end; justify-content:space-between; width:100%; padding:0.08in 1.0in 0.28in; }

  .sig-block { display:flex; flex-direction:column; }
  .sig-label { font-family:'EB Garamond',serif; font-size:10px; color:#888; margin-bottom:3px; }
  .sig-script { font-family:'Dancing Script',cursive; font-size:22px; color:#333; line-height:1; margin-bottom:3px; }
  .sig-line { width:150px; height:1px; background:#aaa; margin-bottom:5px; }
  .sig-name  { font-family:'EB Garamond',serif; font-size:11px; color:#555; }

  .seal-center { display:flex; justify-content:center; align-items:flex-end; }
  .seal-svg { width:68px; height:68px; }

  .qr-wrap { display:flex; flex-direction:column; align-items:flex-end; }
  .qr-img  { width:64px; height:64px; border:1.5px solid ${gold}; padding:2px; }

  .watermark { position:absolute; bottom:4px; left:0; right:0; text-align:center; font-size:8px; color:#ccc; font-family:'EB Garamond',serif; }
</style>
</head>
<body>
<div class="page">
  <!-- Border system -->
  <div class="b-top"></div><div class="b-bottom"></div>
  <div class="b-left"></div><div class="b-right"></div>
  <div class="inner-border"></div>
  <!-- Corners -->
  <div class="c-tl corner-placeholder">${corner}</div>
  <div class="c-tr corner-placeholder">${corner}</div>
  <div class="c-bl corner-placeholder">${corner}</div>
  <div class="c-br corner-placeholder">${corner}</div>

  <div class="content">
    <div class="cert-title-1">${line1}</div>
    ${line2 ? `<div class="cert-title-2">${line2}</div>` : ""}
    <div class="presented-to">This is proudly presented to</div>
    <div class="recipient-name">${recipientName}</div>
    <div class="name-rule"></div>
    ${courseHtml}
    <div class="date-text">Date: ${rawDate}</div>
    ${issuerName ? `<div class="issuer-centered">${issuerName.toUpperCase()}</div>` : ""}
  </div>

  <div class="footer-row">
    <div class="sig-block">
      <div class="sig-label">Authorized Signature:</div>
      <div class="sig-script">${issuerName || "Signature"}</div>
      <div class="sig-line"></div>
      ${issuerTitle ? `<div class="sig-name">${issuerTitle}${issuerName ? ", " + issuerName : ""}</div>` : ""}
    </div>
    <div class="seal-center">${sealSvg}</div>
    ${qrHtml}
  </div>

  ${watermarkHtml}
</div>
</body>
</html>`;
};
