/* ============================================================
   elegant.js — Elegant HTML/CSS certificate template
   Navy + Gold. Full CSS with Google Fonts, gradients, SVG.
   ============================================================ */

module.exports = function elegantTemplate(data, options = {}) {
  const navy  = options.color  || "#1B365D";
  const gold  = options.accent || "#C5A55A";

  const { recipient = {}, certificate = {}, verifyId, qrDataUrl } = data;
  const recipientName = recipient.name            || "Recipient Name";
  const certTitle     = certificate.title         || "Certificate of Completion";
  const courseName    = certificate.course        || "";
  const rawDate       = certificate.date
    ? new Date(certificate.date + "T12:00:00").toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })
    : new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
  const issuerName    = certificate.issuer        || "";
  const issuerTitle   = certificate.issuer_title  || "";
  const watermark     = options.watermark || false;

  const courseHtml = courseName ? `
    <div class="course-label">For successfully completing</div>
    <div class="course-name">${courseName}</div>
  ` : "";

  const qrHtml = qrDataUrl ? `
    <div class="qr-block">
      <img src="${qrDataUrl}" class="qr-img" alt="Verify certificate" />
      ${verifyId ? `<div class="qr-caption">ID: ${verifyId}</div>` : ""}
    </div>
  ` : `<div class="qr-block"></div>`;

  const watermarkHtml = watermark ? `
    <div class="watermark-bar">Generated by BuildCertificates — buildcertificates.com</div>
  ` : "";

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Cinzel:wght@400;600;700&family=Cormorant+Garamond:ital,wght@0,400;0,600;1,400;1,600&family=EB+Garamond:ital,wght@0,400;1,400&display=swap');

  * { margin: 0; padding: 0; box-sizing: border-box; }

  html, body {
    width: 11in;
    height: 8.5in;
    overflow: hidden;
    background: #FDFAF3;
  }

  .page {
    width: 11in;
    height: 8.5in;
    position: relative;
    background: #FDFAF3;
    display: flex;
    flex-direction: column;
    overflow: hidden;
  }

  /* ── Header band ── */
  .header-band {
    background: linear-gradient(135deg, ${navy} 0%, #24477a 60%, #1a3560 100%);
    padding: 0.5in 0.7in 0.45in;
    position: relative;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    flex-shrink: 0;
  }
  .header-band::after {
    content: '';
    position: absolute;
    bottom: -3px;
    left: 0; right: 0;
    height: 5px;
    background: linear-gradient(90deg, transparent 0%, ${gold} 20%, ${gold} 80%, transparent 100%);
  }
  .header-ornament {
    font-size: 11px;
    color: ${gold};
    letter-spacing: 8px;
    margin-bottom: 6px;
    opacity: 0.85;
  }
  .header-title {
    font-family: 'Cinzel', serif;
    font-size: 32px;
    font-weight: 700;
    color: #FFFFFF;
    letter-spacing: 7px;
    text-transform: uppercase;
  }
  .header-rule {
    margin-top: 8px;
    width: 340px;
    height: 1px;
    background: linear-gradient(90deg, transparent, ${gold}, transparent);
  }

  /* ── Body ── */
  .body {
    flex: 1;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    padding: 0.22in 0.7in 0.15in;
    position: relative;
  }

  /* ── Side border bars ── */
  .body::before {
    content: '';
    position: absolute;
    left: 0.28in; top: 0; bottom: 0;
    width: 3px;
    background: linear-gradient(180deg, transparent, ${gold} 20%, ${gold} 80%, transparent);
  }
  .body::after {
    content: '';
    position: absolute;
    right: 0.28in; top: 0; bottom: 0;
    width: 3px;
    background: linear-gradient(180deg, transparent, ${gold} 20%, ${gold} 80%, transparent);
  }

  .presented-to {
    font-family: 'EB Garamond', serif;
    font-style: italic;
    font-size: 14px;
    color: #777;
    margin-bottom: 4px;
    letter-spacing: 1px;
  }

  .recipient-name {
    font-family: 'Cormorant Garamond', serif;
    font-size: 60px;
    font-weight: 600;
    color: ${navy};
    line-height: 1.05;
    text-align: center;
    margin-bottom: 2px;
  }

  .name-rule {
    width: 420px;
    height: 2px;
    background: linear-gradient(90deg, transparent, ${gold} 15%, ${gold} 85%, transparent);
    margin: 8px auto 14px;
  }

  .course-label {
    font-family: 'EB Garamond', serif;
    font-style: italic;
    font-size: 13px;
    color: #666;
    text-align: center;
    margin-bottom: 3px;
  }
  .course-name {
    font-family: 'Cinzel', serif;
    font-size: 15px;
    font-weight: 600;
    color: #333;
    text-align: center;
    letter-spacing: 2px;
    margin-bottom: 10px;
  }

  .date-text {
    font-family: 'EB Garamond', serif;
    font-size: 12px;
    color: #999;
    text-align: center;
    margin-bottom: 0;
  }

  /* ── Footer row ── */
  .footer-row {
    display: flex;
    align-items: flex-end;
    padding: 0.1in 0.55in 0.15in;
    gap: 0;
    flex-shrink: 0;
    border-top: 1px solid rgba(197,165,90,0.25);
  }

  .sig-block {
    flex: 1;
  }
  .sig-label {
    font-family: 'EB Garamond', serif;
    font-size: 9px;
    color: #bbb;
    letter-spacing: 1px;
    text-transform: uppercase;
    margin-bottom: 5px;
  }
  .sig-line {
    width: 160px;
    height: 1px;
    background: #ccc;
    margin-bottom: 6px;
  }
  .sig-name {
    font-family: 'Cinzel', serif;
    font-size: 11px;
    font-weight: 600;
    color: #333;
  }
  .sig-title {
    font-family: 'EB Garamond', serif;
    font-size: 10px;
    color: #888;
    margin-top: 2px;
  }

  .seal-block {
    width: 90px;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    margin-bottom: 4px;
  }
  .seal-ring {
    width: 68px;
    height: 68px;
    border-radius: 50%;
    border: 3px solid ${gold};
    display: flex;
    align-items: center;
    justify-content: center;
    background: transparent;
    position: relative;
  }
  .seal-ring::before {
    content: '';
    position: absolute;
    inset: 5px;
    border-radius: 50%;
    border: 1px solid ${gold};
    opacity: 0.6;
  }
  .seal-icon {
    font-size: 22px;
    color: ${gold};
  }

  .qr-block {
    flex: 1;
    display: flex;
    flex-direction: column;
    align-items: flex-end;
  }
  .qr-img {
    width: 64px;
    height: 64px;
  }
  .qr-caption {
    font-family: 'EB Garamond', serif;
    font-size: 7px;
    color: #ccc;
    margin-top: 3px;
    text-align: right;
  }

  .watermark-bar {
    text-align: center;
    font-size: 8px;
    color: #ccc;
    padding: 3px 0;
    font-family: 'EB Garamond', serif;
    border-top: 1px solid #eee;
    flex-shrink: 0;
  }
</style>
</head>
<body>
<div class="page">

  <div class="header-band">
    <div class="header-ornament">✦ &nbsp;&nbsp;&nbsp; ✦ &nbsp;&nbsp;&nbsp; ✦</div>
    <div class="header-title">${certTitle}</div>
    <div class="header-rule"></div>
  </div>

  <div class="body">
    <div class="presented-to">This is proudly presented to</div>
    <div class="recipient-name">${recipientName}</div>
    <div class="name-rule"></div>
    ${courseHtml}
    <div class="date-text">${rawDate}</div>
  </div>

  <div class="footer-row">
    <div class="sig-block">
      <div class="sig-label">Authorized Signature</div>
      <div class="sig-line"></div>
      ${issuerName  ? `<div class="sig-name">${issuerName}</div>`  : ""}
      ${issuerTitle ? `<div class="sig-title">${issuerTitle}</div>` : ""}
    </div>
    <div class="seal-block">
      <div class="seal-ring">
        <span class="seal-icon">✦</span>
      </div>
    </div>
    ${qrHtml}
  </div>

  ${watermarkHtml}
</div>
</body>
</html>`;
};
