/* ============================================================
   formal.js — Formal/Academic certificate template
   Matches mockup: parchment bg, dark maroon border with SVG
   corner flourishes, ornate scrollwork divider, 68px calligraphic
   name, 2-line recognition text, "ADVANCED WEB DEVELOPMENT"
   large caps, detailed medallion seal left, script sig right,
   date centered bottom, QR bottom-right.
   ============================================================ */

module.exports = function formalTemplate(data, options = {}) {
  const color = options.color || "#6B1D2A";  // Burgundy/maroon
  const gold  = "#B8962E";

  const { recipient = {}, certificate = {}, verifyId, qrDataUrl } = data;
  const recipientName = recipient.name           || "Recipient Name";
  const certTitle     = certificate.title        || "Certificate of Achievement";
  const courseName    = certificate.course       || "";
  const rawDate       = certificate.date
    ? new Date(certificate.date + "T12:00:00").toLocaleDateString("en-US", { year:"numeric", month:"long", day:"numeric" })
    : new Date().toLocaleDateString("en-US", { year:"numeric", month:"long", day:"numeric" });
  const issuerName    = certificate.issuer       || "";
  const issuerTitle   = certificate.issuer_title || "";
  const watermark     = options.watermark || false;

  const watermarkHtml = watermark ? `<div class="watermark">Generated by BuildCertificates — buildcertificates.com</div>` : "";
  const qrHtml = qrDataUrl ? `<img src="${qrDataUrl}" class="qr-img" alt="Verify"/>` : "";

  // SVG corner: leaf/flourish style matching mockup
  const corner = `<svg viewBox="0 0 90 90" xmlns="http://www.w3.org/2000/svg" style="width:90px;height:90px;">
  <!-- Corner lines -->
  <line x1="0" y1="0" x2="90" y2="0"  stroke="${color}" stroke-width="3.5"/>
  <line x1="0" y1="0" x2="0"  y2="90" stroke="${color}" stroke-width="3.5"/>
  <line x1="4" y1="4" x2="88" y2="4"  stroke="${color}" stroke-width="1"/>
  <line x1="4" y1="4" x2="4"  y2="88" stroke="${color}" stroke-width="1"/>
  <!-- Corner leaf ornament -->
  <path d="M10,10 Q20,8 22,18 Q24,28 14,28 Q4,28 6,18 Q8,10 14,12" fill="${color}" opacity="0.85"/>
  <line x1="14" y1="28" x2="14" y2="40" stroke="${color}" stroke-width="1.5"/>
  <path d="M14,40 Q10,36 12,32" stroke="${color}" stroke-width="1" fill="none"/>
  <path d="M14,40 Q18,36 16,32" stroke="${color}" stroke-width="1" fill="none"/>
  <line x1="28" y1="14" x2="40" y2="14" stroke="${color}" stroke-width="1.5"/>
  <path d="M40,14 Q36,10 32,12" stroke="${color}" stroke-width="1" fill="none"/>
  <path d="M40,14 Q36,18 32,16" stroke="${color}" stroke-width="1" fill="none"/>
</svg>`;

  // Ornate scrollwork flourish divider (matching mockup)
  const flourishSvg = `<svg viewBox="0 0 600 28" xmlns="http://www.w3.org/2000/svg" style="width:600px;height:28px;display:block;margin:0 auto;">
  <!-- Center diamond -->
  <rect x="295" y="9" width="10" height="10" fill="${color}" transform="rotate(45,300,14)"/>
  <!-- Left arm -->
  <line x1="0" y1="14" x2="276" y2="14" stroke="${color}" stroke-width="1"/>
  <path d="M276,14 Q284,14 284,8 Q284,2 290,2 Q296,2 296,8" stroke="${color}" stroke-width="1.2" fill="none"/>
  <!-- Right arm (mirror) -->
  <line x1="600" y1="14" x2="324" y2="14" stroke="${color}" stroke-width="1"/>
  <path d="M324,14 Q316,14 316,8 Q316,2 310,2 Q304,2 304,8" stroke="${color}" stroke-width="1.2" fill="none"/>
  <!-- Small inner scrolls left -->
  <path d="M230,14 Q222,14 222,8 Q222,4 228,4" stroke="${color}" stroke-width="0.8" fill="none" opacity="0.7"/>
  <path d="M200,14 Q194,14 194,10" stroke="${color}" stroke-width="0.8" fill="none" opacity="0.5"/>
  <!-- Small inner scrolls right -->
  <path d="M370,14 Q378,14 378,8 Q378,4 372,4" stroke="${color}" stroke-width="0.8" fill="none" opacity="0.7"/>
  <path d="M400,14 Q406,14 406,10" stroke="${color}" stroke-width="0.8" fill="none" opacity="0.5"/>
</svg>`;

  // Medallion seal SVG (detailed, matching mockup bottom-left)
  const medalSvg = `<svg viewBox="0 0 110 110" xmlns="http://www.w3.org/2000/svg" style="width:110px;height:110px;">
  <!-- Outer ring with notches -->
  <circle cx="55" cy="55" r="52" fill="${color}" opacity="0.08"/>
  <circle cx="55" cy="55" r="52" fill="none" stroke="${color}" stroke-width="3"/>
  <circle cx="55" cy="55" r="44" fill="none" stroke="${color}" stroke-width="1.5"/>
  <circle cx="55" cy="55" r="36" fill="none" stroke="${color}" stroke-width="0.8"/>
  <!-- Decorative notches around outer ring -->
  ${Array.from({length:16}, (_,i) => {
    const a = (i/16)*Math.PI*2;
    const x1 = 55 + 48*Math.cos(a), y1 = 55 + 48*Math.sin(a);
    const x2 = 55 + 52*Math.cos(a), y2 = 55 + 52*Math.sin(a);
    return `<line x1="${x1.toFixed(1)}" y1="${y1.toFixed(1)}" x2="${x2.toFixed(1)}" y2="${y2.toFixed(1)}" stroke="${color}" stroke-width="2"/>`;
  }).join("")}
  <!-- Shield inside -->
  <path d="M55,22 L74,28 L74,50 Q74,68 55,78 Q36,68 36,50 L36,28 Z" fill="none" stroke="${color}" stroke-width="1.5"/>
  <!-- Laurel branches inside shield -->
  <path d="M42,60 Q38,55 40,50 Q42,46 45,48" stroke="${color}" stroke-width="1" fill="none"/>
  <path d="M42,60 Q37,57 38,52 Q39,48 42,50" stroke="${color}" stroke-width="0.8" fill="none"/>
  <path d="M68,60 Q72,55 70,50 Q68,46 65,48" stroke="${color}" stroke-width="1" fill="none"/>
  <path d="M68,60 Q73,57 72,52 Q71,48 68,50" stroke="${color}" stroke-width="0.8" fill="none"/>
  <!-- Book / globe icon center -->
  <rect x="46" y="38" width="18" height="12" rx="1" fill="none" stroke="${color}" stroke-width="1.2"/>
  <line x1="55" y1="38" x2="55" y2="50" stroke="${color}" stroke-width="1"/>
  <!-- EST text arc -->
  <text font-family="serif" font-size="6" fill="${color}" font-weight="bold">
    <textPath xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#topArc" startOffset="15%">· EST · ACADEMY OF EXCELLENCE ·</textPath>
  </text>
  <defs>
    <path id="topArc" d="M 10,55 A 45,45 0 1,1 100,55"/>
  </defs>
  <text x="55" y="90" font-family="sans-serif" font-size="5.5" fill="${color}" text-anchor="middle" font-weight="bold" letter-spacing="1">ACADEMY OF EXCELLENCE</text>
</svg>`;

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Cinzel:wght@400;600;700&family=Cormorant+Garamond:ital,wght@0,400;0,600;1,400;1,600;1,700&family=Dancing+Script:wght@500;600&family=IM+Fell+English:ital@0;1&display=swap');
  * { margin:0; padding:0; box-sizing:border-box; }
  html, body { width:11in; height:8.5in; overflow:hidden; background:#F5EDD8; }
  .page { width:11in; height:8.5in; position:relative; background:#F5EDD8; display:flex; flex-direction:column; overflow:hidden; }

  /* ── Parchment texture overlay ── */
  .page::before {
    content:''; position:absolute; inset:0;
    background: radial-gradient(ellipse at 25% 25%, rgba(180,140,60,0.06) 0%, transparent 60%),
                radial-gradient(ellipse at 75% 75%, rgba(120,80,40,0.05) 0%, transparent 60%);
    pointer-events:none; z-index:1;
  }

  /* ── Corners ── */
  .corner { position:absolute; z-index:10; }
  .c-tl { top:0; left:0; }
  .c-tr { top:0; right:0; transform:scaleX(-1); }
  .c-bl { bottom:0; left:0; transform:scaleY(-1); }
  .c-br { bottom:0; right:0; transform:scale(-1); }

  /* ── Border lines ── */
  .b-top    { position:absolute; top:0; left:90px; right:90px; height:3.5px; background:${color}; z-index:5; }
  .b-bottom { position:absolute; bottom:0; left:90px; right:90px; height:3.5px; background:${color}; z-index:5; }
  .b-left   { position:absolute; left:0; top:90px; bottom:90px; width:3.5px; background:${color}; z-index:5; }
  .b-right  { position:absolute; right:0; top:90px; bottom:90px; width:3.5px; background:${color}; z-index:5; }
  /* Inner border */
  .b-top-i    { position:absolute; top:4px; left:94px; right:94px; height:1px; background:${color}; z-index:5; }
  .b-bottom-i { position:absolute; bottom:4px; left:94px; right:94px; height:1px; background:${color}; z-index:5; }
  .b-left-i   { position:absolute; left:4px; top:94px; bottom:94px; width:1px; background:${color}; z-index:5; }
  .b-right-i  { position:absolute; right:4px; top:94px; bottom:94px; width:1px; background:${color}; z-index:5; }

  /* ── Content ── */
  .content { position:relative; z-index:5; display:flex; flex-direction:column; align-items:center; padding:0.6in 1.0in 0; flex:1; }

  .cert-title { font-family:'Cinzel',serif; font-size:30px; font-weight:700; color:${color}; letter-spacing:3px; text-align:center; margin-bottom:10px; }

  .flourish-wrap { margin:0 auto 14px; }

  .presented-to { font-family:'IM Fell English',serif; font-style:italic; font-size:15px; color:#666; text-align:center; margin-bottom:6px; }

  .recipient-name { font-family:'Cormorant Garamond',serif; font-size:70px; font-weight:700; font-style:italic; color:#1a1a1a; text-align:center; line-height:1; margin-bottom:6px; }

  .name-rule { width:400px; height:1px; background:linear-gradient(90deg,transparent,#bbb 20%,#bbb 80%,transparent); margin:0 auto 14px; }

  .recog-text { font-family:'IM Fell English',serif; font-size:14px; color:#555; text-align:center; line-height:1.5; margin-bottom:6px; }

  .course-name { font-family:'Cinzel',serif; font-size:22px; font-weight:700; color:${color}; letter-spacing:3px; text-align:center; text-transform:uppercase; margin-bottom:0; }

  /* ── Bottom row ── */
  .footer-row { position:relative; z-index:5; display:flex; align-items:flex-end; justify-content:space-between; padding:0.12in 0.85in 0.45in; }

  .seal-wrap { flex-shrink:0; }
  .sig-block { display:flex; flex-direction:column; align-items:center; flex:1; }
  .sig-script { font-family:'Dancing Script',cursive; font-size:26px; color:#333; line-height:1; margin-bottom:2px; }
  .sig-line   { width:200px; height:1px; background:#aaa; margin-bottom:7px; }
  .sig-name   { font-family:'Cinzel',serif; font-size:11px; font-weight:600; color:#333; letter-spacing:1px; }
  .sig-title  { font-family:'IM Fell English',serif; font-size:10px; color:#888; font-style:italic; }
  .date-centered { font-family:'IM Fell English',serif; font-size:14px; color:#888; text-align:center; margin-top:6px; }

  .qr-wrap { display:flex; flex-direction:column; align-items:flex-end; flex-shrink:0; }
  .qr-img  { width:60px; height:60px; }

  .watermark { position:absolute; bottom:4px; left:0; right:0; text-align:center; font-size:8px; color:#bbb; font-family:'IM Fell English',serif; z-index:10; }
</style>
</head>
<body>
<div class="page">
  <!-- Border system -->
  <div class="b-top"></div><div class="b-bottom"></div>
  <div class="b-left"></div><div class="b-right"></div>
  <div class="b-top-i"></div><div class="b-bottom-i"></div>
  <div class="b-left-i"></div><div class="b-right-i"></div>
  <!-- Corners -->
  <div class="corner c-tl">${corner}</div>
  <div class="corner c-tr">${corner}</div>
  <div class="corner c-bl">${corner}</div>
  <div class="corner c-br">${corner}</div>

  <div class="content">
    <div class="cert-title">${certTitle}</div>
    <div class="flourish-wrap">${flourishSvg}</div>
    <div class="presented-to">Presented to</div>
    <div class="recipient-name">${recipientName}</div>
    <div class="name-rule"></div>
    ${courseName ? `
      <div class="recog-text">In recognition of successfully completing<br>all requirements for the course</div>
      <div class="course-name">${courseName}</div>
    ` : ""}
  </div>

  <div class="footer-row">
    <div class="seal-wrap">${medalSvg}</div>
    <div class="sig-block">
      <div class="sig-script">${issuerName || "Signature"}</div>
      <div class="sig-line"></div>
      ${issuerTitle ? `<div class="sig-name">${issuerTitle}</div>` : ""}
      ${issuerName  ? `<div class="sig-title">${issuerName}</div>` : ""}
      <div class="date-centered">${rawDate}</div>
    </div>
    <div class="qr-wrap">${qrHtml}</div>
  </div>

  ${watermarkHtml}
</div>
</body>
</html>`;
};
