/* ============================================================
   formal.js — Formal/Academic HTML/CSS certificate template
   Parchment. IM Fell + Cinzel fonts. Ornate SVG borders.
   ============================================================ */

module.exports = function formalTemplate(data, options = {}) {
  const color    = options.color || "#6B1D2A";   // Burgundy
  const gold     = "#B8962E";

  const { recipient = {}, certificate = {}, verifyId, qrDataUrl } = data;
  const recipientName = recipient.name            || "Recipient Name";
  const certTitle     = certificate.title         || "Certificate of Achievement";
  const courseName    = certificate.course        || "";
  const rawDate       = certificate.date
    ? new Date(certificate.date + "T12:00:00").toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })
    : new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
  const issuerName    = certificate.issuer        || "";
  const issuerTitle   = certificate.issuer_title  || "";
  const watermark     = options.watermark || false;

  const courseHtml = courseName ? `
    <div class="course-label">In recognition of completing</div>
    <div class="course-name">${courseName}</div>
  ` : "";

  const qrHtml = qrDataUrl ? `
    <img src="${qrDataUrl}" class="qr-img" alt="Verify" />
    ${verifyId ? `<div class="qr-id">ID: ${verifyId}</div>` : ""}
  ` : "";

  const watermarkHtml = watermark ? `
    <div class="watermark">Generated by BuildCertificates — buildcertificates.com</div>
  ` : "";

  // Corner SVG ornament (top-left)
  const cornerSvg = (flip) => `
    <svg width="70" height="70" viewBox="0 0 70 70" xmlns="http://www.w3.org/2000/svg"
      style="transform:${flip}">
      <rect x="2" y="2" width="20" height="20" fill="${color}" rx="0"/>
      <rect x="5" y="5" width="14" height="14" fill="#FDFAF3" rx="0"/>
      <line x1="22" y1="2" x2="68" y2="2" stroke="${color}" stroke-width="3.5"/>
      <line x1="2" y1="22" x2="2" y2="68" stroke="${color}" stroke-width="3.5"/>
      <line x1="24" y1="5" x2="68" y2="5" stroke="${gold}" stroke-width="0.8" stroke-opacity="0.7"/>
      <line x1="5" y1="24" x2="5" y2="68" stroke="${gold}" stroke-width="0.8" stroke-opacity="0.7"/>
      <rect x="31" y="0" width="8" height="4" fill="${gold}" rx="0" opacity="0.9"/>
      <rect x="0" y="31" width="4" height="8" fill="${gold}" rx="0" opacity="0.9"/>
    </svg>`;

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Cinzel:wght@400;600;700&family=IM+Fell+English:ital@0;1&family=Cormorant+Garamond:ital,wght@0,400;0,600;1,400;1,600;1,700&display=swap');

  * { margin: 0; padding: 0; box-sizing: border-box; }

  html, body {
    width: 11in;
    height: 8.5in;
    overflow: hidden;
    background: #F5EDD8;
  }

  .page {
    width: 11in;
    height: 8.5in;
    position: relative;
    background: #F5EDD8;
    display: flex;
    flex-direction: column;
    overflow: hidden;
  }

  /* ── Corner ornaments ── */
  .corner { position: absolute; z-index: 2; }
  .corner-tl { top: 0; left: 0; }
  .corner-tr { top: 0; right: 0; transform: scaleX(-1); }
  .corner-bl { bottom: 0; left: 0; transform: scaleY(-1); }
  .corner-br { bottom: 0; right: 0; transform: scale(-1); }

  /* ── Outer border lines (connecting corners) ── */
  .border-top    { position: absolute; top: 2px;    left: 72px; right: 72px;  height: 3.5px; background: ${color}; }
  .border-bottom { position: absolute; bottom: 2px; left: 72px; right: 72px;  height: 3.5px; background: ${color}; }
  .border-left   { position: absolute; left: 2px;   top:  72px; bottom: 72px; width:  3.5px; background: ${color}; }
  .border-right  { position: absolute; right: 2px;  top:  72px; bottom: 72px; width:  3.5px; background: ${color}; }

  .border-top-gold    { position: absolute; top: 5px;    left: 76px; right: 76px;  height: 0.8px; background: ${gold}; opacity:0.7; }
  .border-bottom-gold { position: absolute; bottom: 5px; left: 76px; right: 76px;  height: 0.8px; background: ${gold}; opacity:0.7; }
  .border-left-gold   { position: absolute; left: 5px;   top:  76px; bottom: 76px; width:  0.8px; background: ${gold}; opacity:0.7; }
  .border-right-gold  { position: absolute; right: 5px;  top:  76px; bottom: 76px; width:  0.8px; background: ${gold}; opacity:0.7; }

  /* ── Mid-border diamonds ── */
  .mid-diamond {
    position: absolute;
    width: 10px; height: 10px;
    background: ${gold};
    transform: rotate(45deg);
    z-index: 3;
  }
  .md-top    { top: -3px;    left: 50%;  margin-left: -5px; }
  .md-bottom { bottom: -3px; left: 50%;  margin-left: -5px; }
  .md-left   { left: -3px;   top: 50%;   margin-top: -5px; }
  .md-right  { right: -3px;  top: 50%;   margin-top: -5px; }

  /* ── Inner cream panel ── */
  .inner-panel {
    position: absolute;
    top: 0.55in; bottom: 0.55in;
    left: 0.55in; right: 0.55in;
    background: rgba(253,250,243,0.7);
    z-index: 0;
  }

  /* ── Content ── */
  .content {
    position: relative;
    z-index: 5;
    flex: 1;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    padding: 0.6in 0.75in 0.15in;
  }

  .cert-title {
    font-family: 'Cinzel', serif;
    font-size: 28px;
    font-weight: 700;
    color: ${color};
    letter-spacing: 4px;
    text-align: center;
    margin-bottom: 6px;
  }

  /* ── Flourish divider ── */
  .flourish {
    display: flex;
    align-items: center;
    gap: 0;
    width: 460px;
    margin: 0 auto 10px;
  }
  .flourish-line {
    flex: 1;
    height: 1px;
    background: linear-gradient(90deg, transparent, ${color});
  }
  .flourish-line.right {
    background: linear-gradient(90deg, ${color}, transparent);
  }
  .flourish-diamond {
    width: 10px; height: 10px;
    background: ${gold};
    transform: rotate(45deg);
    flex-shrink: 0;
    margin: 0 8px;
  }

  .presented-to {
    font-family: 'IM Fell English', serif;
    font-style: italic;
    font-size: 14px;
    color: #777;
    text-align: center;
    margin-bottom: 5px;
  }

  .recipient-name {
    font-family: 'Cormorant Garamond', serif;
    font-size: 58px;
    font-weight: 700;
    font-style: italic;
    color: #1a1a1a;
    text-align: center;
    line-height: 1.05;
    margin-bottom: 5px;
  }

  .name-rule {
    width: 380px;
    height: 1px;
    background: linear-gradient(90deg, transparent, #ccc 20%, #ccc 80%, transparent);
    margin: 0 auto 12px;
  }

  .course-label {
    font-family: 'IM Fell English', serif;
    font-style: italic;
    font-size: 12px;
    color: #666;
    text-align: center;
    margin-bottom: 4px;
  }
  .course-name {
    font-family: 'Cinzel', serif;
    font-size: 16px;
    font-weight: 600;
    color: ${color};
    letter-spacing: 3px;
    text-transform: uppercase;
    text-align: center;
    margin-bottom: 10px;
  }

  .date-text {
    font-family: 'IM Fell English', serif;
    font-size: 12px;
    color: #999;
    text-align: center;
  }

  /* ── Bottom row ── */
  .footer-row {
    position: relative;
    z-index: 5;
    display: flex;
    align-items: center;
    padding: 0.05in 0.75in 0.45in;
    gap: 0;
  }

  /* Seal */
  .seal {
    width: 80px;
    height: 80px;
    position: relative;
    flex-shrink: 0;
  }
  .seal svg { width: 80px; height: 80px; }

  .sig-block {
    flex: 1;
    text-align: center;
  }
  .sig-line {
    width: 220px;
    height: 1px;
    background: #aaa;
    margin: 0 auto 7px;
  }
  .sig-name {
    font-family: 'Cinzel', serif;
    font-size: 11px;
    font-weight: 600;
    color: #333;
  }
  .sig-title {
    font-family: 'IM Fell English', serif;
    font-size: 10px;
    color: #888;
    margin-top: 2px;
    font-style: italic;
  }

  .qr-block {
    width: 80px;
    display: flex;
    flex-direction: column;
    align-items: flex-end;
    flex-shrink: 0;
  }
  .qr-img {
    width: 58px;
    height: 58px;
  }
  .qr-id {
    font-size: 6px;
    color: #ccc;
    margin-top: 3px;
    font-family: 'IM Fell English', serif;
  }

  .watermark {
    position: relative; z-index: 5;
    text-align: center;
    font-size: 8px;
    color: #bbb;
    padding: 3px 0;
    font-family: 'IM Fell English', serif;
  }
</style>
</head>
<body>
<div class="page">
  <!-- Border system -->
  <div class="border-top"></div>
  <div class="border-bottom"></div>
  <div class="border-left"></div>
  <div class="border-right"></div>
  <div class="border-top-gold"></div>
  <div class="border-bottom-gold"></div>
  <div class="border-left-gold"></div>
  <div class="border-right-gold"></div>

  <!-- Mid-border diamonds -->
  <div class="mid-diamond md-top"></div>
  <div class="mid-diamond md-bottom"></div>
  <div class="mid-diamond md-left"></div>
  <div class="mid-diamond md-right"></div>

  <!-- Corner ornaments -->
  <div class="corner corner-tl">${cornerSvg("none")}</div>
  <div class="corner corner-tr">${cornerSvg("scaleX(-1)")}</div>
  <div class="corner corner-bl">${cornerSvg("scaleY(-1)")}</div>
  <div class="corner corner-br">${cornerSvg("scale(-1)")}</div>

  <!-- Inner panel -->
  <div class="inner-panel"></div>

  <div class="content">
    <div class="cert-title">${certTitle}</div>
    <div class="flourish">
      <div class="flourish-line"></div>
      <div class="flourish-diamond"></div>
      <div class="flourish-line right"></div>
    </div>
    <div class="presented-to">Presented to</div>
    <div class="recipient-name">${recipientName}</div>
    <div class="name-rule"></div>
    ${courseHtml}
    <div class="date-text">${rawDate}</div>
  </div>

  <div class="footer-row">
    <!-- Official seal -->
    <div class="seal">
      <svg viewBox="0 0 80 80" xmlns="http://www.w3.org/2000/svg">
        <circle cx="40" cy="40" r="37" fill="none" stroke="${color}" stroke-width="3"/>
        <circle cx="40" cy="40" r="30" fill="none" stroke="${color}" stroke-width="1"/>
        <circle cx="40" cy="40" r="22" fill="none" stroke="${gold}" stroke-width="0.8" stroke-opacity="0.8"/>
        <text x="40" y="34" font-family="sans-serif" font-size="7" font-weight="bold"
          fill="${color}" text-anchor="middle" letter-spacing="2">OFFICIAL</text>
        <text x="40" y="44" font-family="sans-serif" font-size="11" fill="${gold}" text-anchor="middle">✦</text>
        <text x="40" y="54" font-family="sans-serif" font-size="7" font-weight="bold"
          fill="${color}" text-anchor="middle" letter-spacing="2">SEAL</text>
      </svg>
    </div>

    <div class="sig-block">
      <div class="sig-line"></div>
      ${issuerName  ? `<div class="sig-name">${issuerName}</div>`   : ""}
      ${issuerTitle ? `<div class="sig-title">${issuerTitle}</div>` : ""}
    </div>

    <div class="qr-block">
      ${qrHtml}
    </div>
  </div>

  ${watermarkHtml}
</div>
</body>
</html>`;
};
