/* ============================================================
   formal.js — "Heritage" template
   Midnight navy background, gold everything: double-line border,
   SVG corner ornaments, flourish, 75px gold Cormorant name,
   medallion seal, script signature on cream, gold-bordered QR.
   ============================================================ */

module.exports = function formalTemplate(data, options = {}) {
  const bg   = "#0F1729";  // Midnight navy
  const gold = "#C9A84C";
  const goldLight = "#E8CB7A";
  const cream = "#F5ECD7";

  const { recipient = {}, certificate = {}, verifyId, qrDataUrl } = data;
  const recipientName = recipient.name            || "Recipient Name";
  const certTitle     = certificate.title         || "Certificate of Achievement";
  const courseName    = certificate.course        || "";
  const rawDate       = certificate.date
    ? new Date(certificate.date + "T12:00:00").toLocaleDateString("en-US", { year:"numeric", month:"long", day:"numeric" })
    : new Date().toLocaleDateString("en-US", { year:"numeric", month:"long", day:"numeric" });
  const issuerName    = certificate.issuer        || "";
  const issuerTitle   = certificate.issuer_title  || "";
  const watermark     = options.watermark || false;

  const qrHtml = qrDataUrl
    ? `<img src="${qrDataUrl}" class="qr-img" alt="Verify"/>`
    : "";

  const watermarkHtml = watermark
    ? `<div class="watermark">Generated by BuildCertificates.com</div>`
    : "";

  // Gold corner ornament SVG (top-left; others mirror via CSS transform)
  const corner = `<svg viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg" style="width:100px;height:100px;">
  <!-- Outer L frame -->
  <line x1="0" y1="2" x2="100" y2="2" stroke="${gold}" stroke-width="2.5"/>
  <line x1="2" y1="0" x2="2" y2="100" stroke="${gold}" stroke-width="2.5"/>
  <!-- Inner L frame -->
  <line x1="8" y1="8" x2="100" y2="8" stroke="${gold}" stroke-width="0.8"/>
  <line x1="8" y1="8" x2="8" y2="100" stroke="${gold}" stroke-width="0.8"/>
  <!-- Corner filled ornament -->
  <rect x="0" y="0" width="28" height="28" fill="${gold}" opacity="0.12"/>
  <!-- Diamond at corner junction -->
  <rect x="13" y="13" width="10" height="10" fill="${gold}" transform="rotate(45,18,18)"/>
  <!-- Decorative dots on L arms -->
  <circle cx="46" cy="2" r="2.5" fill="${gold}"/>
  <circle cx="2" cy="46" r="2.5" fill="${gold}"/>
  <!-- Tiny flourish from corner diamond -->
  <path d="M22,10 Q28,8 30,14" stroke="${gold}" stroke-width="0.8" fill="none"/>
  <path d="M10,22 Q8,28 14,30" stroke="${gold}" stroke-width="0.8" fill="none"/>
</svg>`;

  // Central ornamental flourish (top of content)
  const flourish = `<svg viewBox="0 0 700 36" xmlns="http://www.w3.org/2000/svg" style="width:700px;height:36px;display:block;margin:0 auto;">
  <!-- Central diamond cluster -->
  <rect x="344" y="13" width="12" height="12" fill="${gold}" transform="rotate(45,350,19)"/>
  <rect x="338" y="16" width="6" height="6" fill="${gold}" opacity="0.5" transform="rotate(45,341,19)"/>
  <rect x="356" y="16" width="6" height="6" fill="${gold}" opacity="0.5" transform="rotate(45,359,19)"/>
  <!-- Main horizontal rules -->
  <line x1="0" y1="19" x2="322" y2="19" stroke="${gold}" stroke-width="0.8" opacity="0.6"/>
  <line x1="700" y1="19" x2="378" y2="19" stroke="${gold}" stroke-width="0.8" opacity="0.6"/>
  <!-- Decorative inner rule -->
  <line x1="0" y1="23" x2="310" y2="23" stroke="${gold}" stroke-width="0.4" opacity="0.3"/>
  <line x1="700" y1="23" x2="390" y2="23" stroke="${gold}" stroke-width="0.4" opacity="0.3"/>
  <!-- Scroll curves near center -->
  <path d="M322,19 Q330,19 330,12 Q330,5 340,5" stroke="${gold}" stroke-width="1.2" fill="none"/>
  <path d="M378,19 Q370,19 370,12 Q370,5 360,5" stroke="${gold}" stroke-width="1.2" fill="none"/>
  <!-- Smaller scrolls -->
  <path d="M270,19 Q278,19 278,14 Q278,9 285,9" stroke="${gold}" stroke-width="0.8" fill="none" opacity="0.6"/>
  <path d="M430,19 Q422,19 422,14 Q422,9 415,9" stroke="${gold}" stroke-width="0.8" fill="none" opacity="0.6"/>
  <circle cx="285" cy="9" r="2" fill="${gold}" opacity="0.5"/>
  <circle cx="415" cy="9" r="2" fill="${gold}" opacity="0.5"/>
</svg>`;

  // Medallion seal SVG
  const medal = `<svg viewBox="0 0 120 120" xmlns="http://www.w3.org/2000/svg" style="width:105px;height:105px;">
  <!-- Outer decorative ring with notches -->
  <circle cx="60" cy="60" r="57" fill="${bg}" stroke="${gold}" stroke-width="2.5"/>
  <circle cx="60" cy="60" r="50" fill="none" stroke="${gold}" stroke-width="0.8"/>
  <circle cx="60" cy="60" r="43" fill="none" stroke="${gold}" stroke-width="0.4" stroke-dasharray="2,3"/>
  <!-- Notch marks -->
  ${Array.from({length:24},(_,i)=>{
    const a=(i/24)*Math.PI*2, x1=(60+53*Math.cos(a)).toFixed(1), y1=(60+53*Math.sin(a)).toFixed(1), x2=(60+57*Math.cos(a)).toFixed(1), y2=(60+57*Math.sin(a)).toFixed(1);
    return `<line x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}" stroke="${gold}" stroke-width="1.8"/>`;
  }).join('')}
  <!-- Laurel left path -->
  <path d="M22,68 Q14,58 18,47 Q22,37 29,40 Q24,50 27,58 Q29,65 22,68Z" fill="${gold}" opacity="0.7"/>
  <path d="M26,76 Q17,68 20,57 Q23,47 31,50 Q26,60 28,68 Q30,74 26,76Z" fill="${gold}" opacity="0.55"/>
  <!-- Laurel right path -->
  <path d="M98,68 Q106,58 102,47 Q98,37 91,40 Q96,50 93,58 Q91,65 98,68Z" fill="${gold}" opacity="0.7"/>
  <path d="M94,76 Q103,68 100,57 Q97,47 89,50 Q94,60 92,68 Q90,74 94,76Z" fill="${gold}" opacity="0.55"/>
  <!-- Center shield -->
  <path d="M60,22 L80,30 L80,56 Q80,76 60,86 Q40,76 40,56 L40,30 Z" fill="${gold}" opacity="0.12"/>
  <path d="M60,22 L80,30 L80,56 Q80,76 60,86 Q40,76 40,56 L40,30 Z" fill="none" stroke="${gold}" stroke-width="1.5"/>
  <!-- Book in shield -->
  <rect x="50" y="42" width="20" height="14" rx="1" fill="none" stroke="${goldLight}" stroke-width="1.2"/>
  <line x1="60" y1="42" x2="60" y2="56" stroke="${goldLight}" stroke-width="1"/>
  <line x1="53" y1="46" x2="58" y2="46" stroke="${goldLight}" stroke-width="0.7"/>
  <line x1="53" y1="49" x2="58" y2="49" stroke="${goldLight}" stroke-width="0.7"/>
  <line x1="62" y1="46" x2="67" y2="46" stroke="${goldLight}" stroke-width="0.7"/>
  <line x1="62" y1="49" x2="67" y2="49" stroke="${goldLight}" stroke-width="0.7"/>
  <!-- Globe below book -->
  <circle cx="60" cy="68" r="6" fill="none" stroke="${gold}" stroke-width="1"/>
  <line x1="54" y1="68" x2="66" y2="68" stroke="${gold}" stroke-width="0.7"/>
  <path d="M60,62 Q64,68 60,74" stroke="${gold}" stroke-width="0.7" fill="none"/>
  <path d="M60,62 Q56,68 60,74" stroke="${gold}" stroke-width="0.7" fill="none"/>
  <!-- Bottom label -->
  <text x="60" y="100" font-family="sans-serif" font-size="6" font-weight="bold" fill="${gold}" text-anchor="middle" letter-spacing="2">OFFICIAL SEAL</text>
</svg>`;

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Cinzel:wght@400;600;700&family=Cormorant+Garamond:ital,wght@0,400;0,600;1,400;1,600;1,700&family=Dancing+Script:wght@600;700&family=EB+Garamond:ital,wght@0,400;1,400&display=swap');

  * { margin:0; padding:0; box-sizing:border-box; }
  html, body { width:11in; height:8.5in; overflow:hidden; background:${bg}; }
  .page { width:11in; height:8.5in; position:relative; background:${bg}; display:flex; flex-direction:column; overflow:hidden; }

  /* Subtle noise texture overlay */
  .page::before {
    content:''; position:absolute; inset:0; z-index:0; pointer-events:none;
    background: radial-gradient(ellipse at 30% 20%, rgba(201,168,76,0.04) 0%, transparent 55%),
                radial-gradient(ellipse at 70% 80%, rgba(201,168,76,0.04) 0%, transparent 55%);
  }

  /* ── Corner ornaments ── */
  .corner { position:absolute; z-index:5; }
  .c-tl { top:0; left:0; }
  .c-tr { top:0; right:0; transform:scaleX(-1); }
  .c-bl { bottom:0; left:0; transform:scaleY(-1); }
  .c-br { bottom:0; right:0; transform:scale(-1); }

  /* ── Border lines ── */
  .border-outer-h { position:absolute; left:100px; right:100px; height:2.5px; background:${gold}; z-index:4; }
  .border-outer-v { position:absolute; top:100px; bottom:100px; width:2.5px; background:${gold}; z-index:4; }
  .boh-t { top:2px; } .boh-b { bottom:2px; }
  .bov-l { left:2px; } .bov-r { right:2px; }

  .border-inner-h { position:absolute; left:108px; right:108px; height:0.8px; background:${gold}; opacity:0.5; z-index:4; }
  .border-inner-v { position:absolute; top:108px; bottom:108px; width:0.8px; background:${gold}; opacity:0.5; z-index:4; }
  .bih-t { top:8px; } .bih-b { bottom:8px; }
  .biv-l { left:8px; } .biv-r { right:8px; }

  /* ── Content ── */
  .content {
    position: relative; z-index:2;
    display: flex; flex-direction:column; align-items:center;
    padding: 0.55in 1.1in 0.15in;
    flex: 1;
  }

  .cert-title {
    font-family: 'Cinzel', serif;
    font-size: 22px; font-weight: 700;
    color: ${gold};
    letter-spacing: 8px;
    text-align: center;
    margin-bottom: 0.12in;
  }

  .flourish-wrap { margin-bottom: 0.12in; }

  .presented {
    font-family: 'EB Garamond', serif;
    font-style: italic;
    font-size: 15px;
    color: rgba(245,236,215,0.6);
    margin-bottom: 0.04in;
    text-align: center;
  }

  /* Recipient name — giant gold calligraphy */
  .recipient-name {
    font-family: 'Cormorant Garamond', serif;
    font-size: 78px;
    font-weight: 700;
    font-style: italic;
    color: ${gold};
    text-align: center;
    line-height: 1;
    letter-spacing: 1px;
    margin-bottom: 0.08in;
    /* Gold text glow */
    text-shadow: 0 0 40px rgba(201,168,76,0.25), 0 2px 4px rgba(0,0,0,0.5);
  }

  .name-rule {
    width: 500px;
    height: 1px;
    background: linear-gradient(90deg, transparent, ${gold} 20%, ${gold} 80%, transparent);
    margin: 0 auto 0.12in;
  }

  .recog-text {
    font-family: 'EB Garamond', serif;
    font-style: italic;
    font-size: 14px;
    color: rgba(245,236,215,0.65);
    text-align: center;
    line-height: 1.6;
    margin-bottom: 0.06in;
  }

  .course-name {
    font-family: 'Cinzel', serif;
    font-size: 18px;
    font-weight: 700;
    color: ${goldLight};
    letter-spacing: 4px;
    text-align: center;
    text-transform: uppercase;
    margin-bottom: 0;
  }

  /* ── Footer ── */
  .footer {
    position: relative; z-index:2;
    display: flex; align-items: flex-end; justify-content: space-between;
    padding: 0 1.0in 0.38in;
  }

  /* Left: seal */
  .seal-wrap { flex-shrink:0; }

  /* Center: signature block */
  .sig-block { flex:1; display:flex; flex-direction:column; align-items:center; }
  .sig-script { font-family:'Dancing Script',cursive; font-size:28px; color:${cream}; line-height:1; margin-bottom:5px; }
  .sig-line-gold { width:200px; height:1px; background:linear-gradient(90deg,transparent,${gold} 30%,${gold} 70%,transparent); margin-bottom:6px; }
  .sig-name  { font-family:'Cinzel',serif; font-size:11px; font-weight:600; color:${gold}; letter-spacing:2px; margin-bottom:3px; }
  .sig-title { font-family:'EB Garamond',serif; font-size:10px; color:rgba(245,236,215,0.55); font-style:italic; }
  .sig-date  { font-family:'EB Garamond',serif; font-size:12px; color:${gold}; opacity:0.7; margin-top:6px; }

  /* Right: QR */
  .qr-wrap { flex-shrink:0; display:flex; flex-direction:column; align-items:flex-end; }
  .qr-img  { width:62px; height:62px; border:1.5px solid ${gold}; padding:3px; background:#fff; filter:grayscale(0.3); }

  .watermark { position:absolute; bottom:3px; left:0; right:0; text-align:center; font-size:8px; color:rgba(201,168,76,0.3); font-family:'EB Garamond',serif; z-index:5; }
</style>
</head>
<body>
<div class="page">
  <!-- Border system -->
  <div class="border-outer-h boh-t"></div>
  <div class="border-outer-h boh-b"></div>
  <div class="border-outer-v bov-l"></div>
  <div class="border-outer-v bov-r"></div>
  <div class="border-inner-h bih-t"></div>
  <div class="border-inner-h bih-b"></div>
  <div class="border-inner-v biv-l"></div>
  <div class="border-inner-v biv-r"></div>

  <!-- Corner ornaments -->
  <div class="corner c-tl">${corner}</div>
  <div class="corner c-tr">${corner}</div>
  <div class="corner c-bl">${corner}</div>
  <div class="corner c-br">${corner}</div>

  <!-- Main content -->
  <div class="content">
    <div class="cert-title">${certTitle}</div>
    <div class="flourish-wrap">${flourish}</div>
    <div class="presented">Presented to</div>
    <div class="recipient-name">${recipientName}</div>
    <div class="name-rule"></div>
    ${courseName ? `
    <div class="recog-text">In recognition of outstanding completion of</div>
    <div class="course-name">${courseName}</div>
    ` : ""}
  </div>

  <!-- Footer -->
  <div class="footer">
    <div class="seal-wrap">${medal}</div>
    <div class="sig-block">
      <div class="sig-script">${issuerName || "Signature"}</div>
      <div class="sig-line-gold"></div>
      ${issuerTitle ? `<div class="sig-name">${issuerTitle}</div>` : ""}
      ${issuerName  ? `<div class="sig-title">${issuerName}</div>`  : ""}
      <div class="sig-date">${rawDate}</div>
    </div>
    <div class="qr-wrap">${qrHtml}</div>
  </div>

  ${watermarkHtml}
</div>
</body>
</html>`;
};
