/* ============================================================
   modern.js — Modern HTML/CSS certificate template
   Geometric, bold. Inter font. Indigo accent with tint panel.
   ============================================================ */

module.exports = function modernTemplate(data, options = {}) {
  const color    = options.color || "#4F46E5";
  const colorDark = shadeColor(color, -20);
  const colorTint = hexToRgba(color, 0.07);

  const { recipient = {}, certificate = {}, verifyId, qrDataUrl } = data;
  const recipientName = recipient.name            || "Recipient Name";
  const certTitle     = certificate.title         || "Certificate of Completion";
  const courseName    = certificate.course        || "";
  const rawDate       = certificate.date
    ? new Date(certificate.date + "T12:00:00").toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })
    : new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
  const issuerName    = certificate.issuer        || "";
  const issuerTitle   = certificate.issuer_title  || "";
  const watermark     = options.watermark || false;

  const courseHtml = courseName ? `
    <div class="course-text">For successfully completing <strong>${courseName}</strong></div>
  ` : "";

  const qrHtml = qrDataUrl ? `
    <div class="qr-section">
      <img src="${qrDataUrl}" class="qr-img" alt="Verify" />
      ${verifyId ? `<div class="qr-id">${verifyId}</div>` : ""}
    </div>
  ` : "";

  const watermarkHtml = watermark ? `
    <div class="watermark">Generated by BuildCertificates — buildcertificates.com</div>
  ` : "";

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600;700;800&display=swap');

  * { margin: 0; padding: 0; box-sizing: border-box; }

  html, body {
    width: 11in;
    height: 8.5in;
    overflow: hidden;
    background: #fff;
  }

  .page {
    width: 11in;
    height: 8.5in;
    position: relative;
    background: #FFFFFF;
    display: flex;
    overflow: hidden;
  }

  /* ── Left accent column ── */
  .left-col {
    width: 18px;
    background: linear-gradient(180deg, ${color} 0%, ${colorDark} 100%);
    flex-shrink: 0;
    position: relative;
  }
  .left-col::after {
    content: '';
    position: absolute;
    top: 0; bottom: 0;
    right: -5px;
    width: 3px;
    background: ${colorTint};
  }

  /* ── Main content ── */
  .main {
    flex: 1;
    display: flex;
    flex-direction: column;
    padding: 0;
  }

  /* ── Top band ── */
  .top-band {
    height: 8px;
    background: linear-gradient(90deg, ${color}, ${colorDark});
    flex-shrink: 0;
  }

  .content {
    flex: 1;
    display: flex;
    flex-direction: column;
    justify-content: center;
    padding: 0.35in 0.65in 0.25in;
  }

  /* ── Tint block behind name ── */
  .name-block {
    background: ${colorTint};
    border-left: 4px solid ${color};
    padding: 0.2in 0.25in 0.18in;
    margin-bottom: 0.18in;
    position: relative;
  }
  .name-block::after {
    content: '';
    position: absolute;
    right: 0; top: 0; bottom: 0;
    width: 4px;
    background: ${color};
    opacity: 0.25;
  }

  .type-label {
    font-family: 'Inter', sans-serif;
    font-size: 10px;
    font-weight: 700;
    color: ${color};
    letter-spacing: 6px;
    text-transform: uppercase;
    margin-bottom: 10px;
  }

  .recipient-name {
    font-family: 'Inter', sans-serif;
    font-size: 62px;
    font-weight: 800;
    color: #111;
    line-height: 1;
    letter-spacing: -1px;
  }

  .course-text {
    font-family: 'Inter', sans-serif;
    font-size: 15px;
    font-weight: 400;
    color: #555;
    margin-top: 8px;
  }
  .course-text strong {
    color: #222;
    font-weight: 600;
  }

  /* ── Divider ── */
  .divider {
    height: 1px;
    background: linear-gradient(90deg, #e5e7eb 0%, #e5e7eb 70%, transparent 100%);
    margin: 0.22in 0 0.18in;
  }

  /* ── Bottom row ── */
  .bottom-row {
    display: flex;
    align-items: flex-start;
    gap: 0.3in;
  }

  .issuer-block {
    flex: 1;
  }
  .issuer-accent {
    width: 40px;
    height: 3px;
    background: ${color};
    border-radius: 2px;
    margin-bottom: 8px;
  }
  .issuer-name {
    font-family: 'Inter', sans-serif;
    font-size: 13px;
    font-weight: 700;
    color: #111;
    margin-bottom: 2px;
  }
  .issuer-title {
    font-family: 'Inter', sans-serif;
    font-size: 11px;
    font-weight: 400;
    color: #888;
  }

  .date-block {
    text-align: right;
  }
  .date-label {
    font-family: 'Inter', sans-serif;
    font-size: 8px;
    font-weight: 700;
    color: #bbb;
    letter-spacing: 3px;
    text-transform: uppercase;
    margin-bottom: 5px;
  }
  .date-value {
    font-family: 'Inter', sans-serif;
    font-size: 13px;
    font-weight: 600;
    color: #333;
  }

  .qr-section {
    display: flex;
    flex-direction: column;
    align-items: center;
  }
  .qr-img {
    width: 64px;
    height: 64px;
  }
  .qr-id {
    font-family: 'Inter', sans-serif;
    font-size: 6px;
    color: #ccc;
    margin-top: 3px;
    text-align: center;
  }

  /* ── Bottom band ── */
  .bottom-band {
    height: 8px;
    background: linear-gradient(90deg, ${color}, ${colorDark});
    flex-shrink: 0;
    margin-top: auto;
  }

  .watermark {
    text-align: center;
    font-size: 8px;
    color: #bbb;
    padding: 3px 0;
    font-family: 'Inter', sans-serif;
    flex-shrink: 0;
  }
</style>
</head>
<body>
<div class="page">
  <div class="left-col"></div>
  <div class="main">
    <div class="top-band"></div>

    <div class="content">
      <div class="name-block">
        <div class="type-label">${certTitle}</div>
        <div class="recipient-name">${recipientName}</div>
        ${courseHtml}
      </div>

      <div class="divider"></div>

      <div class="bottom-row">
        ${qrHtml}
        <div class="issuer-block">
          <div class="issuer-accent"></div>
          ${issuerName  ? `<div class="issuer-name">${issuerName}</div>`   : ""}
          ${issuerTitle ? `<div class="issuer-title">${issuerTitle}</div>` : ""}
        </div>
        <div class="date-block">
          <div class="date-label">Date Issued</div>
          <div class="date-value">${rawDate}</div>
        </div>
      </div>
    </div>

    <div class="bottom-band"></div>
    ${watermarkHtml}
  </div>
</div>
</body>
</html>`;
};

function shadeColor(hex, percent) {
  const num = parseInt(hex.replace("#",""),16);
  const amt = Math.round(2.55 * percent);
  const R = Math.max(0,Math.min(255,(num>>16)+amt));
  const G = Math.max(0,Math.min(255,((num>>8)&0x00FF)+amt));
  const B = Math.max(0,Math.min(255,(num&0x0000FF)+amt));
  return "#"+((1<<24)+(R<<16)+(G<<8)+B).toString(16).slice(1);
}

function hexToRgba(hex, alpha) {
  const num = parseInt(hex.replace("#",""),16);
  return `rgba(${num>>16},${(num>>8)&0xFF},${num&0xFF},${alpha})`;
}
