/* ============================================================
   modern.js — Modern certificate template
   Matches mockup: white bg, thick indigo top bar, small caps
   title, 80px black name, large gray course text, date +
   "Acme Academy ___Signature___" bottom row, QR bottom-left.
   ============================================================ */

module.exports = function modernTemplate(data, options = {}) {
  const color = options.color || "#4F46E5";

  const { recipient = {}, certificate = {}, verifyId, qrDataUrl } = data;
  const recipientName = recipient.name           || "Recipient Name";
  const certTitle     = certificate.title        || "Certificate of Completion";
  const courseName    = certificate.course       || "";
  const rawDate       = certificate.date
    ? new Date(certificate.date + "T12:00:00").toLocaleDateString("en-US", { year:"numeric", month:"long", day:"numeric" })
    : new Date().toLocaleDateString("en-US", { year:"numeric", month:"long", day:"numeric" });
  const issuerName    = certificate.issuer       || "";
  const issuerTitle   = certificate.issuer_title || "";
  const watermark     = options.watermark || false;

  const qrHtml = qrDataUrl ? `<img src="${qrDataUrl}" class="qr-img" alt="Verify" />` : "";
  const watermarkHtml = watermark ? `<div class="watermark">Generated by BuildCertificates — buildcertificates.com</div>` : "";

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700;800;900&family=Dancing+Script:wght@600&display=swap');
  * { margin:0; padding:0; box-sizing:border-box; }
  html, body { width:11in; height:8.5in; overflow:hidden; background:#fff; }
  .page { width:11in; height:8.5in; position:relative; background:#fff; display:flex; flex-direction:column; overflow:hidden; }

  /* ── Top bar ── */
  .top-bar { height:18px; background:${color}; flex-shrink:0; }

  /* ── Main content ── */
  .content { flex:1; display:flex; flex-direction:column; justify-content:flex-start; padding:0.6in 0.75in 0.2in; }

  .type-label { font-family:'Inter',sans-serif; font-size:15px; font-weight:700; color:${color}; letter-spacing:5px; text-transform:uppercase; margin-bottom:18px; }

  .recipient-name { font-family:'Inter',sans-serif; font-size:82px; font-weight:900; color:#111; line-height:1; letter-spacing:-2px; margin-bottom:18px; }

  .course-block { margin-bottom:auto; }
  .course-line1 { font-family:'Inter',sans-serif; font-size:24px; font-weight:600; color:#777; line-height:1.3; }
  .course-line2 { font-family:'Inter',sans-serif; font-size:24px; font-weight:600; color:#777; line-height:1.3; }

  /* ── Bottom section ── */
  .bottom-section { padding:0 0 0.5in; }

  .meta-row { display:flex; align-items:flex-end; gap:0.5in; margin-bottom:0.22in; }
  .date-issuer { display:flex; flex-direction:column; gap:2px; }
  .date-val    { font-family:'Inter',sans-serif; font-size:16px; font-weight:400; color:#111; }
  .issuer-val  { font-family:'Inter',sans-serif; font-size:16px; font-weight:700; color:#111; }

  .sig-group { display:flex; align-items:flex-end; gap:12px; }
  .sig-script { font-family:'Dancing Script',cursive; font-size:28px; color:#333; line-height:1; margin-bottom:-4px; }
  .sig-line   { width:200px; height:1px; background:#ccc; margin-bottom:8px; }

  .qr-row { display:flex; align-items:center; }
  .qr-img { width:56px; height:56px; }

  .watermark { text-align:center; font-size:8px; color:#ccc; padding:4px 0; font-family:'Inter',sans-serif; }
</style>
</head>
<body>
<div class="page">
  <div class="top-bar"></div>

  <div class="content">
    <div class="type-label">${certTitle}</div>
    <div class="recipient-name">${recipientName}</div>
    ${courseName ? `
    <div class="course-block">
      <div class="course-line1">For successfully completing</div>
      <div class="course-line2">${courseName}</div>
    </div>` : ""}
  </div>

  <div class="bottom-section">
    <div class="meta-row" style="padding:0 0.75in;">
      <div class="date-issuer">
        <div class="date-val">${rawDate}</div>
        ${issuerName ? `<div class="issuer-val">${issuerName}</div>` : ""}
      </div>
      <div class="sig-group">
        ${issuerTitle || issuerName ? `<div class="sig-script">${issuerTitle || issuerName}</div>` : `<div class="sig-script">Signature</div>`}
        <div class="sig-line"></div>
      </div>
    </div>
    <div class="qr-row" style="padding:0 0.75in;">
      ${qrHtml}
    </div>
  </div>

  ${watermarkHtml}
</div>
</body>
</html>`;
};
